# External Secrets Operator configuration for ScholarLink Billing Service
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scholarlink-billing-secrets
  namespace: scholarlink-prod
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: scholarlink-billing-env
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /prod/scholarlink/billing/DATABASE_URL
    - secretKey: JWT_PUBLIC_KEY
      remoteRef:
        key: /prod/scholarlink/billing/JWT_PUBLIC_KEY
    - secretKey: JWT_ISSUER
      remoteRef:
        key: /prod/scholarlink/billing/JWT_ISSUER
    - secretKey: JWT_AUDIENCE
      remoteRef:
        key: /prod/scholarlink/billing/JWT_AUDIENCE
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: /prod/scholarlink/billing/STRIPE_SECRET_KEY
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: /prod/scholarlink/billing/STRIPE_WEBHOOK_SECRET
    - secretKey: WEBHOOK_SHARED_SECRET
      remoteRef:
        key: /prod/scholarlink/billing/WEBHOOK_SHARED_SECRET

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scholarlink-billing-config
  namespace: scholarlink-prod
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  TRUST_PROXY: "true"
  CORS_ALLOWED_ORIGINS: "https://student-pilot.replit.app,https://admin.student-pilot.replit.app"
  BILLING_ROUNDING_MODE: "precise"
  RATE_CARD_VERSION: "v1"
  REQUESTS_PER_MINUTE: "100"
  PRISMA_POOL_MIN: "2"
  PRISMA_POOL_MAX: "10"
  READINESS_STARTUP_GRACE_SECONDS: "30"