# Pre-deployment database migration job
apiVersion: batch/v1
kind: Job
metadata:
  name: scholarlink-billing-migrate
  namespace: scholarlink-prod
  labels:
    app: scholarlink-billing
    component: migration
spec:
  template:
    metadata:
      labels:
        app: scholarlink-billing
        component: migration
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: migrate
        image: scholarlink/billing:latest@sha256:REPLACE_WITH_ACTUAL_DIGEST
        imagePullPolicy: Always
        command: ["npm", "run", "db:migrate"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: scholarlink-billing-env
              key: DATABASE_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: scholarlink-billing-config
              key: NODE_ENV
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: npm-cache
          mountPath: /.npm
      volumes:
      - name: tmp
        emptyDir: {}
      - name: npm-cache
        emptyDir: {}