# Automated Secrets Rotation for ScholarLink Production
# Handles JWT keys, database credentials, and API keys

---
# JWT Key Rotation CronJob (Quarterly)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jwt-key-rotation
  namespace: scholarlink-prod
  labels:
    app: scholarlink
    component: security
spec:
  schedule: "0 2 1 */3 *"  # First day of quarter at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: scholarlink
            component: jwt-rotation
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            fsGroup: 1001
          containers:
          - name: jwt-rotator
            image: scholarlink/tools:latest
            command: ["/bin/sh", "-c"]
            args:
            - |
              set -euo pipefail
              echo "🔄 Starting JWT key rotation - $(date)"
              
              # Generate new JWT key pair
              openssl genrsa -out /tmp/jwt_private_new.pem 4096
              openssl rsa -in /tmp/jwt_private_new.pem -pubout -out /tmp/jwt_public_new.pem
              
              # Generate key ID (kid) for JWKS
              NEW_KID=$(openssl rand -hex 8)
              echo "Generated new key ID: $NEW_KID"
              
              # Create JWKS format
              cat > /tmp/jwks.json << EOF
              {
                "keys": [
                  {
                    "kty": "RSA",
                    "use": "sig",
                    "kid": "$NEW_KID",
                    "n": "$(openssl rsa -in /tmp/jwt_private_new.pem -noout -modulus | sed 's/Modulus=//' | xxd -r -p | base64 -w 0 | tr '+/' '-_' | tr -d '=')",
                    "e": "AQAB"
                  }
                ]
              }
              EOF
              
              # Store in AWS Secrets Manager
              NEW_JWT_SECRET=$(cat << EOF
              {
                "private_key": "$(cat /tmp/jwt_private_new.pem | base64 -w 0)",
                "public_key": "$(cat /tmp/jwt_public_new.pem | base64 -w 0)",
                "kid": "$NEW_KID",
                "jwks": $(cat /tmp/jwks.json)
              }
              EOF
              )
              
              # Update AWS Secrets Manager with dual-key approach
              aws secretsmanager update-secret \
                --secret-id "scholarlink/prod/jwt-new" \
                --secret-string "$NEW_JWT_SECRET" \
                --region "$AWS_REGION"
              
              # Notify about rotation
              curl -X POST "$SLACK_WEBHOOK" \
                -H "Content-Type: application/json" \
                -d "{\"text\":\"🔄 JWT key rotation initiated. New key ID: $NEW_KID. Manual promotion required.\"}"
              
              echo "✅ JWT key rotation prepared. Manual promotion required."
              
            env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: SLACK_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: scholarlink-external
                  key: SLACK_WEBHOOK
                  optional: true
            
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
          
          volumes:
          - name: tmp
            emptyDir: {}

---
# Database Password Rotation Job (Monthly)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-password-rotation
  namespace: scholarlink-prod
  labels:
    app: scholarlink
    component: security
spec:
  schedule: "0 3 1 * *"  # First day of month at 3 AM
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            fsGroup: 1001
          containers:
          - name: db-rotator
            image: postgres:15-alpine
            command: ["/bin/sh", "-c"]
            args:
            - |
              set -euo pipefail
              echo "🔄 Starting database password rotation - $(date)"
              
              # Generate new secure password
              NEW_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)
              
              # Update password in database
              psql "$DATABASE_URL" -c "ALTER USER $PGUSER WITH PASSWORD '$NEW_PASSWORD';"
              
              # Update AWS Secrets Manager
              NEW_DB_SECRET=$(cat << EOF
              {
                "DATABASE_URL": "postgresql://$PGUSER:$NEW_PASSWORD@$PGHOST:$PGPORT/$PGDATABASE?sslmode=require",
                "PGHOST": "$PGHOST",
                "PGPORT": "$PGPORT", 
                "PGUSER": "$PGUSER",
                "PGPASSWORD": "$NEW_PASSWORD",
                "PGDATABASE": "$PGDATABASE"
              }
              EOF
              )
              
              aws secretsmanager update-secret \
                --secret-id "scholarlink/prod/database" \
                --secret-string "$NEW_DB_SECRET" \
                --region "$AWS_REGION"
              
              # Test new connection
              NEW_DATABASE_URL="postgresql://$PGUSER:$NEW_PASSWORD@$PGHOST:$PGPORT/$PGDATABASE?sslmode=require"
              psql "$NEW_DATABASE_URL" -c "SELECT 1;" > /dev/null
              
              echo "✅ Database password rotation completed successfully"
              
            env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: scholarlink-database
                  key: DATABASE_URL
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: scholarlink-database
                  key: PGHOST
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: scholarlink-database
                  key: PGPORT
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: scholarlink-database
                  key: PGUSER
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: scholarlink-database
                  key: PGDATABASE
            
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"

---
# Manual JWT Key Promotion Job Template
apiVersion: batch/v1
kind: Job
metadata:
  name: jwt-key-promotion-template
  namespace: scholarlink-prod
  labels:
    app: scholarlink
    component: security
spec:
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: jwt-promoter
        image: scholarlink/tools:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -euo pipefail
          echo "🔄 Promoting new JWT keys to active - $(date)"
          
          # Get new JWT keys from AWS Secrets Manager
          NEW_JWT_SECRET=$(aws secretsmanager get-secret-value \
            --secret-id "scholarlink/prod/jwt-new" \
            --region "$AWS_REGION" \
            --query SecretString --output text)
          
          # Move new keys to active
          aws secretsmanager update-secret \
            --secret-id "scholarlink/prod/jwt" \
            --secret-string "$NEW_JWT_SECRET" \
            --region "$AWS_REGION"
          
          # Update Kubernetes secret for immediate deployment pickup
          kubectl create secret generic scholarlink-jwt-keys-new \
            --from-literal=jwt_private.pem="$(echo "$NEW_JWT_SECRET" | jq -r .private_key | base64 -d)" \
            --from-literal=jwt_public.pem="$(echo "$NEW_JWT_SECRET" | jq -r .public_key | base64 -d)" \
            --namespace=scholarlink-prod \
            --dry-run=client -o yaml | kubectl apply -f -
          
          # Trigger rolling restart to pick up new keys
          kubectl rollout restart deployment/scholarlink-app -n scholarlink-prod
          
          # Wait for rollout to complete
          kubectl rollout status deployment/scholarlink-app -n scholarlink-prod --timeout=300s
          
          # Update existing secret after successful rollout
          kubectl delete secret scholarlink-jwt-keys -n scholarlink-prod
          kubectl create secret generic scholarlink-jwt-keys \
            --from-literal=jwt_private.pem="$(echo "$NEW_JWT_SECRET" | jq -r .private_key | base64 -d)" \
            --from-literal=jwt_public.pem="$(echo "$NEW_JWT_SECRET" | jq -r .public_key | base64 -d)" \
            --namespace=scholarlink-prod
          
          kubectl delete secret scholarlink-jwt-keys-new -n scholarlink-prod
          
          echo "✅ JWT key promotion completed successfully"
          
        env:
        - name: AWS_REGION
          value: "us-east-1"
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      
      # Allow access to Kubernetes API
      serviceAccountName: jwt-key-rotator

---
# Service Account for JWT rotation with appropriate permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jwt-key-rotator
  namespace: scholarlink-prod

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jwt-key-rotator
  namespace: scholarlink-prod
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jwt-key-rotator
  namespace: scholarlink-prod
subjects:
- kind: ServiceAccount
  name: jwt-key-rotator
  namespace: scholarlink-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jwt-key-rotator