# Vulnerability Scanning and Security Monitoring for ScholarLink

---
# Trivy vulnerability scanner CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-image-scan
  namespace: scholarlink-prod
  labels:
    app: scholarlink
    component: security-scanning
spec:
  schedule: "0 6 * * *"  # Daily at 6 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: scholarlink
            component: trivy-scan
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            fsGroup: 1001
          containers:
          - name: trivy-scanner
            image: aquasec/trivy:latest
            command: ["/bin/sh", "-c"]
            args:
            - |
              set -euo pipefail
              echo "ðŸ” Starting vulnerability scan - $(date)"
              
              # Get current image digest from deployment
              CURRENT_IMAGE=$(kubectl get deployment scholarlink-app -n scholarlink-prod -o jsonpath='{.spec.template.spec.containers[0].image}')
              echo "Scanning image: $CURRENT_IMAGE"
              
              # Perform comprehensive scan
              trivy image \
                --format json \
                --output /tmp/scan-results.json \
                --severity HIGH,CRITICAL \
                --exit-code 1 \
                --no-progress \
                --timeout 10m \
                "$CURRENT_IMAGE"
              
              SCAN_EXIT_CODE=$?
              
              # Generate human-readable report
              trivy image \
                --format table \
                --output /tmp/scan-report.txt \
                --severity HIGH,CRITICAL \
                --no-progress \
                "$CURRENT_IMAGE" || true
              
              # Count vulnerabilities
              HIGH_COUNT=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH")] | length' /tmp/scan-results.json 2>/dev/null || echo "0")
              CRITICAL_COUNT=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "CRITICAL")] | length' /tmp/scan-results.json 2>/dev/null || echo "0")
              
              echo "Scan Results:"
              echo "- Critical vulnerabilities: $CRITICAL_COUNT"
              echo "- High vulnerabilities: $HIGH_COUNT"
              
              # Send to monitoring system
              curl -X POST "http://prometheus-pushgateway:9091/metrics/job/vulnerability-scan/instance/scholarlink" \
                --data "vulnerability_scan_critical_count $CRITICAL_COUNT" || true
              
              curl -X POST "http://prometheus-pushgateway:9091/metrics/job/vulnerability-scan/instance/scholarlink" \
                --data "vulnerability_scan_high_count $HIGH_COUNT" || true
              
              # Send alert if critical vulnerabilities found
              if [ "$CRITICAL_COUNT" -gt 0 ]; then
                curl -X POST "$SLACK_WEBHOOK" \
                  -H "Content-Type: application/json" \
                  -d "{\"text\":\"ðŸš¨ CRITICAL: $CRITICAL_COUNT critical vulnerabilities found in ScholarLink image $CURRENT_IMAGE\"}" || true
              fi
              
              # Send weekly summary (on Mondays)
              if [ "$(date +%u)" = "1" ]; then
                REPORT_SUMMARY=$(head -20 /tmp/scan-report.txt)
                curl -X POST "$SLACK_WEBHOOK" \
                  -H "Content-Type: application/json" \
                  -d "{\"text\":\"ðŸ“Š Weekly Security Scan Summary:\n\`\`\`$REPORT_SUMMARY\`\`\`\"}" || true
              fi
              
              # Exit with scan result code
              exit $SCAN_EXIT_CODE
              
            env:
            - name: SLACK_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: scholarlink-external
                  key: SLACK_WEBHOOK
                  optional: true
            
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
            
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            
            volumeMounts:
            - name: tmp
              mountPath: /tmp
          
          volumes:
          - name: tmp
            emptyDir: {}
          
          # Service account for Kubernetes API access
          serviceAccountName: trivy-scanner

---
# Falco runtime security monitoring
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: scholarlink-prod
  labels:
    app: falco
    component: runtime-security
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8765"
    spec:
      serviceAccountName: falco
      hostNetwork: true
      hostPID: true
      containers:
      - name: falco
        image: falcosecurity/falco:latest
        args:
        - /usr/bin/falco
        - --cri=/run/containerd/containerd.sock
        - --k8s-api=https://kubernetes.default.svc
        - --k8s-api-cert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --k8s-api-token=/var/run/secrets/kubernetes.io/serviceaccount/token
        - -pk
        env:
        - name: FALCO_GRPC_ENABLED
          value: "true"
        - name: FALCO_GRPC_BIND_ADDRESS
          value: "0.0.0.0:5060"
        - name: FALCO_HTTP_OUTPUT_ENABLED
          value: "true"
        - name: FALCO_HTTP_OUTPUT_URL
          value: "http://scholarlink-falco-webhook:8080/webhook"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/var/run/docker.sock
          name: docker-socket
          readOnly: true
        - mountPath: /host/run/containerd/containerd.sock
          name: containerd-socket
          readOnly: true
        - mountPath: /host/dev
          name: dev-fs
          readOnly: true
        - mountPath: /host/proc
          name: proc-fs
          readOnly: true
        - mountPath: /host/boot
          name: boot-fs
          readOnly: true
        - mountPath: /host/lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /host/usr
          name: usr-fs
          readOnly: true
        - mountPath: /host/etc
          name: etc-fs
          readOnly: true
        - mountPath: /etc/falco/rules.d
          name: falco-rules
          readOnly: true
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: containerd-socket
        hostPath:
          path: /run/containerd/containerd.sock
      - name: dev-fs
        hostPath:
          path: /dev
      - name: proc-fs
        hostPath:
          path: /proc
      - name: boot-fs
        hostPath:
          path: /boot
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-fs
        hostPath:
          path: /usr
      - name: etc-fs
        hostPath:
          path: /etc
      - name: falco-rules
        configMap:
          name: falco-rules

---
# Custom Falco rules for ScholarLink
apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-rules
  namespace: scholarlink-prod
data:
  scholarlink_rules.yaml: |
    # Custom Falco rules for ScholarLink application security
    
    - rule: ScholarLink Suspicious Database Access
      desc: Detect suspicious database access patterns in ScholarLink
      condition: >
        spawned_process and
        container.name startswith "scholarlink" and
        proc.name in (psql, mysql, sqlite3) and
        not proc.pname in (node, npm, tsx)
      output: >
        Suspicious database access in ScholarLink container
        (user=%user.name command=%proc.cmdline container=%container.name pod=%k8s.pod.name)
      priority: WARNING
      tags: [database, suspicious]
    
    - rule: ScholarLink Unauthorized File Access
      desc: Detect unauthorized file system access in ScholarLink containers
      condition: >
        open_read and
        container.name startswith "scholarlink" and
        fd.name startswith "/etc/passwd" or
        fd.name startswith "/etc/shadow" or
        fd.name startswith "/root"
      output: >
        Unauthorized file access in ScholarLink container
        (user=%user.name file=%fd.name container=%container.name pod=%k8s.pod.name)
      priority: CRITICAL
      tags: [filesystem, unauthorized]
    
    - rule: ScholarLink Network Anomaly
      desc: Detect unexpected network connections from ScholarLink
      condition: >
        outbound and
        container.name startswith "scholarlink" and
        not fd.rip in (169.254.169.254, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16) and
        not fd.rport in (443, 80, 53, 5432, 6379)
      output: >
        Unexpected network connection from ScholarLink
        (user=%user.name connection=%fd.rip:%fd.rport container=%container.name pod=%k8s.pod.name)
      priority: WARNING
      tags: [network, anomaly]
    
    - rule: ScholarLink Container Escape Attempt
      desc: Detect potential container escape attempts
      condition: >
        spawned_process and
        container.name startswith "scholarlink" and
        proc.name in (chroot, pivot_root, unshare, nsenter) and
        not proc.pname in (node, npm, tsx)
      output: >
        Potential container escape attempt in ScholarLink
        (user=%user.name command=%proc.cmdline container=%container.name pod=%k8s.pod.name)
      priority: CRITICAL
      tags: [container-escape, critical]

---
# Service account for Trivy scanner
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-scanner
  namespace: scholarlink-prod

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trivy-scanner
  namespace: scholarlink-prod
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trivy-scanner
  namespace: scholarlink-prod
subjects:
- kind: ServiceAccount
  name: trivy-scanner
  namespace: scholarlink-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trivy-scanner

---
# Service account for Falco
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: scholarlink-prod

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces", "pods", "replicationcontrollers", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco
subjects:
- kind: ServiceAccount
  name: falco
  namespace: scholarlink-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: falco